services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "4444:3000"
      - "4001:4002"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  selenium_chrome:
    image: selenium/standalone-chrome
    logging:
      driver: none
    ports:
      - "5900:4444"

  redis:
    image: redis
  database:
    image: postgres
    env_file:
     - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
