on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build -f Dockerfile.prod . --tag ghcr.io/msypniewski511/rails_6_in_docker:latest
          # docker run ghcr.io/msypniewski511/rails_6_in_docker:latest
          docker push ghcr.io/msypniewski511/rails_6_in_docker:latest